name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: build
      run: |
        npm install grunt-cli -g
        npm install
        grunt
        yarn
        yarn test        
    - name: publish
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: endsWith(github.ref, '/master')  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
