name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: build
      run: |
        npm install grunt-cli -g
        npm install
        npm run build --if-present
        grunt
    - name: publish
      if: endsWith(github.ref, '/master')  
      run: |
        mv dist /tmp/
        git checkout gh-pages
        rm -rf dist
        mv /tmp/dist ./
        git add dist/
        git commit -m 'publish from ${{ github.ref }}'
        git push origin gh-pages
        git checkout master
