name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: build
      run: |
        npm install grunt-cli -g
        npm install
        npm run build --if-present
        yarn
        yarn test
    - name: publish
      uses: JamesIves/github-pages-deploy-action@master
      if: endsWith(github.ref, '/master')  
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: grunt
